#!/usr/bin/env Rscript
# =============================================================================
# build_dashboard.R — FluxCourseForecast 2026
# Generates exercises/dashboard.html: a self-contained offline HTML dashboard
# embedding all data, Plotly.js, and interactive JS/CSS in one file.
#
# Sites: US-NR1, US-MMS (with SSEM); DE-Tha, DK-Sor (FLUXNET/FLUXCOM/CMIP6 only)
#
# Data sources:
#   SSEM (sub-daily)   : 2008 single-year RDS files (US-NR1, US-MMS only)
#   SSEM (daily+)      : full-record RDS from exercises/run_full_record.R (US-NR1, US-MMS)
#   FLUXNET sub-daily  : 2008 from HH/HR CSVs, all four sites, thinned every 4th step
#   FLUXNET daily      : DD CSVs filtered to 2000-2025
#   FLUXCOM monthly    : 2001-2021 (all four sites)
#   CMIP6 monthly      : filtered to 2000-2021 (all four sites)
#
# Run from the repo root:  Rscript exercises/build_dashboard.R
# Output:                  exercises/dashboard.html
# =============================================================================

suppressPackageStartupMessages({
  library(jsonlite)
  library(dplyr)
  library(lubridate)
  library(readr)
})

Sys.setenv(RENV_CONFIG_SYNCHRONIZED_CHECK = "FALSE")

cat("=== FluxCourseForecast 2026 — Dashboard Builder ===\n\n")

# ─── Paths ────────────────────────────────────────────────────────────────────
DATA_DIR     <- "data"
OUT_HTML     <- "exercises/dashboard.html"
PLOTLY_CACHE <- "exercises/.plotly.min.js"   # cached, gitignored

# ─── Physical constants and conversion factors ────────────────────────────────
# μmol CO2 m-2 s-1 × step_seconds × 12.011e-6 g/μmol = gC m-2 per step
# For daily total: sum over steps × (step_s × 12.011e-6)
UMOL_TO_GC_PER_S <- 12.011e-6   # g C per μmol CO2

# kg C m-2 s-1 → gC m-2 d-1
KGC_S_TO_GC_DAY <- 1e3 * 86400

# W m-2 (latent heat) → mm d-1 (ET); λ = 2.45 MJ kg-1
LE_TO_MM_DAY <- 86400 / 2.45e6

# SSEM output variable indices (1-based R; order matches varnames in functions.R):
# Bleaf Bwood BSOM LAI GPP NEP Ra NPPw NPPl Rh litter mort
I_LAI <- 4L; I_GPP <- 5L; I_NEP <- 6L; I_RA <- 7L; I_RH <- 10L

rnd <- function(x, d = 4) round(x, d)

# ─── Helpers: ensemble CI and daily aggregation ───────────────────────────────

# Quantile CI across ensemble dimension of a matrix [n_time x n_ens]
ens_ci <- function(m) {
  q <- apply(m, 1, quantile, c(0.025, 0.5, 0.975), na.rm = TRUE)
  list(lo = rnd(q[1, ]), med = rnd(q[2, ]), hi = rnd(q[3, ]))
}

# Aggregate sub-daily SSEM array to daily carbon fluxes (gC m-2 d-1) and LAI
agg_to_daily <- function(arr, steps_per_day, step_s) {
  n     <- dim(arr)[1]
  n_d   <- n %/% steps_per_day
  n_use <- n_d * steps_per_day
  a     <- arr[seq_len(n_use), , , drop = FALSE]
  di    <- rep(seq_len(n_d), each = steps_per_day)
  conv  <- step_s * UMOL_TO_GC_PER_S   # per-step → gC m-2

  agg_flux_ci <- function(vi, negate = FALSE) {
    m <- apply(a[, , vi], 2, function(e) tapply(e * (if (negate) -1 else 1), di, sum) * conv)
    ens_ci(m)
  }
  agg_lai_ci <- function() {
    m <- apply(a[, , I_LAI], 2, function(e) tapply(e, di, mean))
    ens_ci(m)
  }

  list(
    n_days  = n_d,
    gpp = agg_flux_ci(I_GPP),
    nee = agg_flux_ci(I_NEP, negate = TRUE),  # NEE = -NEP
    rh  = agg_flux_ci(I_RH),
    ra  = agg_flux_ci(I_RA),
    lai = agg_lai_ci()
  )
}


# =============================================================================
# SSEM processors
# =============================================================================

# ─── Sub-daily display from 2008 single-year RDS ─────────────────────────────
# The 2008 RDS files are plain arrays (not lists) generated by Exercise 01.
# We use them only for the sub-daily timescale view (2008 representative year).
proc_ssem_subdaily_2008 <- function(rds_path, steps_per_day, run_year = 2008L) {
  cat(sprintf("  SSEM sub-daily 2008 [spd=%d] %s...\n",
              steps_per_day, basename(rds_path)))
  arr    <- readRDS(rds_path)                              # plain array
  step_s <- (24L * 60L / steps_per_day) * 60L
  n_use  <- dim(arr)[1]

  # Thin the sub-daily series to every 4th timestep to reduce JSON size:
  #   US-NR1 (48/day): every 4th → 12 points/day (2-hourly equivalent)
  #   US-MMS (24/day): every 4th →  6 points/day (4-hourly equivalent)
  si  <- seq(1L, n_use, 4L)
  dt0 <- as.POSIXct(sprintf("%d-01-01 00:00:00", run_year), tz = "UTC")
  sdt <- format(dt0 + (si - 1L) * step_s, "%Y-%m-%dT%H:%M", tz = "UTC")

  # Instantaneous median across ensemble members (not daily-integrated)
  sd_med <- function(vi, negate = FALSE) {
    raw <- arr[si, , vi]
    rnd(apply(raw, 1, median, na.rm = TRUE) * (if (negate) -1 else 1), 3)
  }

  list(
    dates = sdt,
    gpp   = sd_med(I_GPP),
    nee   = sd_med(I_NEP, negate = TRUE),
    rh    = sd_med(I_RH),
    lai   = rnd(apply(arr[si, , I_LAI], 1, median, na.rm = TRUE), 3)
  )
}


# ─── Daily / monthly / annual from full-record RDS ───────────────────────────
# The full-record RDS is a list produced by exercises/run_full_record.R.
# It contains a 3-D array [total_timesteps × ne × 12] plus metadata.
proc_ssem_full <- function(rds_path, site_id) {
  cat(sprintf("  SSEM full-record [%s] %s...\n", site_id, basename(rds_path)))
  meta          <- readRDS(rds_path)
  arr           <- meta$output
  years_present <- meta$years
  spd           <- meta$steps_per_day      # steps per day
  step_s        <- (24L * 60L / spd) * 60L

  # ── Build the day-level date sequence for the full record ───────────────
  # Each year contributes n_days × steps_per_day timesteps.
  # We regenerate the date vector from the year metadata so there is no
  # possibility of drift from the actual data timestamps.
  all_dates_d <- character(0)
  for (yr in years_present) {
    n_days      <- if (leap_year(yr)) 366L else 365L
    all_dates_d <- c(all_dates_d,
                     format(seq.Date(as.Date(sprintf("%d-01-01", yr)),
                                     by = "day", length.out = n_days)))
  }

  # ── Aggregate to daily ──────────────────────────────────────────────────
  dd <- agg_to_daily(arr, spd, step_s)

  # ── Trim to 2000-2025 ───────────────────────────────────────────────────
  # The first two SSEM years (1998-1999) serve as carbon pool spin-up.
  # Removing them keeps the displayed record within the 2000-2025 window
  # used consistently across all data sources in this dashboard.
  keep        <- all_dates_d >= "2000-01-01" & all_dates_d <= "2025-12-31"
  all_dates_d <- all_dates_d[keep]
  trim_ci <- function(ci) list(lo = ci$lo[keep], med = ci$med[keep], hi = ci$hi[keep])
  dd$gpp  <- trim_ci(dd$gpp)
  dd$nee  <- trim_ci(dd$nee)
  dd$rh   <- trim_ci(dd$rh)
  dd$ra   <- trim_ci(dd$ra)
  dd$lai  <- trim_ci(dd$lai)

  # ── Monthly aggregation: average daily values within each year-month ────
  # 'ym' is a character vector like "1998-01", "1998-01", ..., "2023-12"
  # One value per calendar day.
  ym       <- substr(all_dates_d, 1, 7)
  ym_uniq  <- unique(ym)
  dates_m  <- paste0(ym_uniq, "-01")

  mo_mean  <- function(v) rnd(vapply(ym_uniq, function(m) mean(v[ym == m], na.rm = TRUE), numeric(1)))

  # ── Annual aggregation: sum of daily gC m-2 d-1 = gC m-2 yr-1 ──────────
  yr_str   <- substr(all_dates_d, 1, 4)
  yr_uniq  <- unique(yr_str)

  ann_sum  <- function(v) rnd(vapply(yr_uniq, function(y) sum( v[yr_str == y], na.rm = TRUE), numeric(1)), 1)
  ann_mean <- function(v) rnd(vapply(yr_uniq, function(y) mean(v[yr_str == y], na.rm = TRUE), numeric(1)), 3)

  list(
    daily = list(
      dates   = all_dates_d,
      gpp_med = dd$gpp$med, gpp_lo = dd$gpp$lo, gpp_hi = dd$gpp$hi,
      nee_med = dd$nee$med, nee_lo = dd$nee$lo, nee_hi = dd$nee$hi,
      rh_med  = dd$rh$med,  rh_lo  = dd$rh$lo,  rh_hi  = dd$rh$hi,
      lai_med = dd$lai$med, lai_lo = dd$lai$lo,  lai_hi = dd$lai$hi
    ),
    monthly = list(
      dates = dates_m,
      gpp   = mo_mean(dd$gpp$med),
      nee   = mo_mean(dd$nee$med),
      rh    = mo_mean(dd$rh$med),
      lai   = mo_mean(dd$lai$med)
    ),
    annual = list(
      year    = as.integer(yr_uniq),
      gpp     = ann_sum(dd$gpp$med),
      nee     = ann_sum(dd$nee$med),
      rh      = ann_sum(dd$rh$med),
      lai_avg = ann_mean(dd$lai$med)
    )
  )
}


# =============================================================================
# FLUXNET daily processor — full record (all available years)
# =============================================================================

proc_fluxnet <- function(csv_path, site_id) {
  cat(sprintf("  FLUXNET full-record [%s] %s...\n", site_id, basename(csv_path)))
  is_nr1   <- site_id == "US-NR1"
  nee_col  <- if (is_nr1) "NEE_CUT_REF"     else "NEE_VUT_REF"
  nee_qc   <- if (is_nr1) "NEE_CUT_REF_QC"  else "NEE_VUT_REF_QC"
  gpp_col  <- if (is_nr1) "GPP_NT_CUT_REF"  else "GPP_NT_VUT_REF"
  reco_col <- if (is_nr1) "RECO_NT_CUT_REF" else "RECO_NT_VUT_REF"

  df <- read_csv(csv_path, show_col_types = FALSE) |>
    mutate(across(where(is.numeric), ~ replace(., . == -9999, NA))) |>
    mutate(date = as.Date(as.character(DATE))) |>
    # Limit to 2000-2025 to match the global date range of the dashboard
    filter(date >= as.Date("2000-01-01"), date <= as.Date("2025-12-31"))

  # Carbon fluxes: μmol m-2 s-1 × 86400 s/d × 12.011e-6 g/μmol = gC m-2 d-1
  C    <- UMOL_TO_GC_PER_S * 86400
  nee  <- rnd(df[[nee_col]]  * C)
  gpp  <- rnd(df[[gpp_col]]  * C)
  reco <- rnd(df[[reco_col]] * C)
  qc   <- df[[nee_qc]]

  # Energy (W m-2) and ET from LE (mm d-1)
  le <- rnd(df[["LE_F_MDS"]], 2)
  h  <- rnd(df[["H_F_MDS"]],  2)
  sw <- rnd(df[["SW_IN_F"]],  2)
  lw <- rnd(df[["LW_IN_F"]],  2)
  ta <- rnd(df[["TA_F"]],     2)
  et <- rnd(df[["LE_F_MDS"]] * LE_TO_MM_DAY, 3)

  dates_d <- format(df$date)

  # Monthly: average daily values within each year-month
  ym      <- substr(dates_d, 1, 7)
  ym_uniq <- unique(ym)
  dates_m <- paste0(ym_uniq, "-01")
  mm      <- function(v) rnd(vapply(ym_uniq, function(m) mean(v[ym == m], na.rm = TRUE), numeric(1)))

  # Annual: sum of daily gC m-2 d-1 = gC m-2 yr-1
  yr_str  <- substr(dates_d, 1, 4)
  yr_uniq <- unique(yr_str)
  ann_sum <- function(v) rnd(vapply(yr_uniq, function(y) sum(v[yr_str == y], na.rm = TRUE), numeric(1)), 1)

  list(
    daily = list(
      dates  = dates_d,
      nee    = nee, gpp = gpp, reco = reco, nee_qc = as.integer(qc),
      le = le, h = h, sw = sw, lw = lw, et = et, ta = ta
    ),
    monthly = list(
      dates = dates_m,
      nee   = mm(nee), gpp = mm(gpp), reco = mm(reco),
      le = mm(le), h = mm(h), et = mm(et)
    ),
    annual = list(
      year = as.integer(yr_uniq),
      gpp  = ann_sum(gpp),
      nee  = ann_sum(nee)
    )
  )
}


# =============================================================================
# FLUXCOM monthly processor (unchanged — 2001–2021)
# =============================================================================

proc_fluxcom <- function(csv_path) {
  cat(sprintf("  FLUXCOM %s...\n", basename(csv_path)))
  df <- read.csv(csv_path, comment.char = "#") |>
    mutate(date  = as.Date(paste(year, month, "01", sep = "-")),
           days  = days_in_month(date))

  # Annual: sum(gC m-2 d-1 × days) = gC m-2 yr-1
  ann <- df |>
    group_by(year) |>
    summarise(gpp = rnd(sum(GPP_gC_m2_d * days, na.rm = TRUE), 1),
              nee = rnd(sum(NEE_gC_m2_d * days, na.rm = TRUE), 1),
              .groups = "drop")

  list(
    monthly = list(
      dates = format(df$date),
      gpp   = rnd(df$GPP_gC_m2_d),
      nee   = rnd(df$NEE_gC_m2_d),
      et    = rnd(df$ET_mm_d),
      ter   = rnd(df$TER_gC_m2_d)
    ),
    annual = list(year = ann$year, gpp = ann$gpp, nee = ann$nee)
  )
}


# =============================================================================
# CMIP6 monthly processor (unchanged — 1980–2021)
# =============================================================================

proc_cmip6 <- function(csv_path, model_name) {
  cat(sprintf("  CMIP6 [%s] %s...\n", model_name, basename(csv_path)))
  df <- read_csv(csv_path, show_col_types = FALSE) |>
    # Trim CMIP6 to 2000-2021; pre-2000 historical data is outside the dashboard window
    filter(year >= 2000L) |>
    mutate(
      date = as.Date(paste(year, month, "01", sep = "-")),
      days = days_in_month(date),
      gpp  = rnd(gpp_kgC_m2_s  * KGC_S_TO_GC_DAY),
      rh   = rnd(rh_kgC_m2_s   * KGC_S_TO_GC_DAY),
      ra   = rnd(ra_kgC_m2_s   * KGC_S_TO_GC_DAY),
      # NEE = Ra + Rh - GPP (positive = net emission; approximation from model outputs)
      nee  = rnd((ra_kgC_m2_s + rh_kgC_m2_s - gpp_kgC_m2_s) * KGC_S_TO_GC_DAY),
      lai  = rnd(lai_m2_m2, 3),
      le   = rnd(latent_heat_W_m2,   2),
      h    = rnd(sensible_heat_W_m2, 2),
      sw   = rnd(sw_down_sfc_W_m2,   2),
      et   = rnd(latent_heat_W_m2 * LE_TO_MM_DAY, 3)
    )

  scen <- df$scenario[1]

  ann <- df |>
    group_by(year) |>
    summarise(
      gpp     = rnd(sum(gpp * days, na.rm = TRUE), 1),
      nee     = rnd(sum(nee * days, na.rm = TRUE), 1),
      rh      = rnd(sum(rh  * days, na.rm = TRUE), 1),
      lai_avg = rnd(mean(lai, na.rm = TRUE), 3),
      .groups = "drop"
    )

  list(
    scenario = scen,
    monthly  = list(
      dates = format(df$date),
      gpp   = df$gpp, nee = df$nee, rh = df$rh,
      lai   = df$lai, le  = df$le,  h  = df$h,
      sw    = df$sw,  et  = df$et
    ),
    annual = list(year = ann$year, gpp = ann$gpp, nee = ann$nee,
                  rh = ann$rh, lai_avg = ann$lai_avg)
  )
}


# =============================================================================
# FLUXNET sub-daily processor — 2008 only, all four sites
# =============================================================================
# Loads 2008 half-hourly (or hourly for US-MMS) NEE and met observations.
# QC flag is retained so the dashboard can colour-code points by data quality.
# Only the needed columns are read to keep memory use manageable — HH files
# are 600-700 MB but col_select lets readr skip unwanted columns.
#
# Returns NULL if no data is found for the requested year.

proc_fluxnet_subdaily <- function(csv_path, site_id, year = 2008L) {
  cat(sprintf("  FLUXNET sub-daily %d [%s] %s...\n", year, site_id, basename(csv_path)))
  is_nr1  <- site_id == "US-NR1"
  is_mms  <- site_id == "US-MMS"
  nee_col <- if (is_nr1) "NEE_CUT_REF"    else "NEE_VUT_REF"
  nee_qc  <- if (is_nr1) "NEE_CUT_REF_QC" else "NEE_VUT_REF_QC"
  ts_col  <- if (is_mms) "TIMESTAMP_START" else "DATETIME_START"

  # Read only the 7 needed columns; avoids loading the full 200-column HH file
  df <- read_csv(csv_path, show_col_types = FALSE,
                 col_select = any_of(c(ts_col, nee_col, nee_qc,
                                       "SW_IN_F", "TA_F", "LE_F_MDS", "H_F_MDS"))) |>
    mutate(across(where(is.numeric), ~ replace(., . == -9999, NA)))

  # Parse timestamp to POSIXct — two formats depending on site
  if (is_mms) {
    # US-MMS HR: TIMESTAMP_START is an integer YYYYMMDDHHMM (e.g. 200801010000)
    df <- df |>
      mutate(dt = as.POSIXct(strptime(as.character(.data[[ts_col]]),
                                       "%Y%m%d%H%M", tz = "UTC")))
  } else {
    # HH sites (US-NR1, DE-Tha, DK-Sor): DATETIME_START is ISO 8601 with Z suffix;
    # readr already parses it as POSIXct so we just rename the column
    df <- df |> mutate(dt = .data[[ts_col]])
  }

  # Filter to the target year
  df <- df |> filter(year(dt) == year)

  if (nrow(df) == 0L) {
    warning(sprintf("proc_fluxnet_subdaily: no data for %d in %s", year, basename(csv_path)))
    return(NULL)
  }

  # Thin to every 4th timestep — consistent with SSEM sub-daily thinning:
  #   HH sites (48 steps/day): every 4th -> 12 points/day (2-hourly equivalent)
  #   HR sites (24 steps/day): every 4th ->  6 points/day (4-hourly equivalent)
  si <- seq(1L, nrow(df), 4L)
  df <- df[si, ]

  list(
    dates  = format(df$dt, "%Y-%m-%dT%H:%M", tz = "UTC"),
    nee    = rnd(df[[nee_col]], 3),
    nee_qc = as.integer(df[[nee_qc]]),
    sw     = rnd(df$SW_IN_F,  2),
    ta     = rnd(df$TA_F,     2),
    le     = rnd(df$LE_F_MDS, 2),
    h      = rnd(df$H_F_MDS,  2),
    et     = rnd(df$LE_F_MDS * LE_TO_MM_DAY, 3)
  )
}


# =============================================================================
# Assemble all data
# =============================================================================

cat("Processing data...\n")

# ── Check which SSEM RDS files are available ──────────────────────────────────
# The full-record RDS files are generated by exercises/run_full_record.R.
# If they do not exist yet, fall back to the 2008 single-year files for all
# timescales and print a warning.
nr1_full_rds <- file.path(DATA_DIR, "ssem_usnr1_fullrecord.rds")
mms_full_rds <- file.path(DATA_DIR, "ssem_usmms_fullrecord.rds")
nr1_2008_rds <- file.path(DATA_DIR, "ssem_usnr1_2008.rds")
mms_2008_rds <- file.path(DATA_DIR, "ssem_usmms_2008.rds")

if (!file.exists(nr1_full_rds) || !file.exists(mms_full_rds)) {
  stop(
    "Full-record RDS files not found:\n",
    "  ", nr1_full_rds, "\n",
    "  ", mms_full_rds, "\n",
    "Run exercises/run_full_record.R first to generate them, then re-run this script."
  )
}

# ── Process SSEM sub-daily (2008 only; used for the Sub-daily tab) ────────────
cat("Processing SSEM 2008 sub-daily...\n")

nr1_subdaily <- proc_ssem_subdaily_2008(nr1_2008_rds, steps_per_day = 48L)
mms_subdaily <- proc_ssem_subdaily_2008(mms_2008_rds, steps_per_day = 24L)

# ── Process SSEM full-record (daily / monthly / annual tabs) ─────────────────
cat("Processing SSEM full-record (daily/monthly/annual)...\n")

nr1_full <- proc_ssem_full(nr1_full_rds, "US-NR1")
mms_full <- proc_ssem_full(mms_full_rds, "US-MMS")

# ── Process FLUXNET daily (full record, filtered to 2000-2025) ────────────────
cat("Processing FLUXNET daily (full record)...\n")
nr1_fluxnet    <- proc_fluxnet(file.path(DATA_DIR, "US-NR1", "US-NR1_DD.csv"), "US-NR1")
mms_fluxnet    <- proc_fluxnet(file.path(DATA_DIR, "US-MMS", "US-MMS_DD.csv"), "US-MMS")
detha_fluxnet  <- proc_fluxnet(file.path(DATA_DIR, "DE-Tha", "DE-Tha_DD.csv"), "DE-Tha")
dksor_fluxnet  <- proc_fluxnet(file.path(DATA_DIR, "DK-Sor", "DK-Sor_DD.csv"), "DK-Sor")

# ── Process FLUXNET sub-daily (2008, all four sites) ─────────────────────────
# Note: HH files are 600-700 MB; col_select limits the columns read but the
# full file is still scanned, so this step takes ~60 s total across four sites.
cat("Processing FLUXNET 2008 sub-daily (all sites)...\n")
nr1_fluxnet_sd   <- proc_fluxnet_subdaily(
  file.path(DATA_DIR, "US-NR1", "US-NR1_HH.csv"), "US-NR1")
mms_fluxnet_sd   <- proc_fluxnet_subdaily(
  file.path(DATA_DIR, "US-MMS", "US-MMS_HR.csv"), "US-MMS")
detha_fluxnet_sd <- proc_fluxnet_subdaily(
  file.path(DATA_DIR, "DE-Tha", "DE-Tha_HH.csv"), "DE-Tha")
dksor_fluxnet_sd <- proc_fluxnet_subdaily(
  file.path(DATA_DIR, "DK-Sor", "DK-Sor_HH.csv"), "DK-Sor")

# ── Process FLUXCOM (all four sites) ─────────────────────────────────────────
cat("Processing FLUXCOM...\n")
nr1_fluxcom   <- proc_fluxcom(file.path(DATA_DIR, "fluxcom", "US-NR1_fluxcom_monthly.csv"))
mms_fluxcom   <- proc_fluxcom(file.path(DATA_DIR, "fluxcom", "US-MMS_fluxcom_monthly.csv"))
detha_fluxcom <- proc_fluxcom(file.path(DATA_DIR, "fluxcom", "DE-Tha_fluxcom_monthly.csv"))
dksor_fluxcom <- proc_fluxcom(file.path(DATA_DIR, "fluxcom", "DK-Sor_fluxcom_monthly.csv"))

# ── Process CMIP6 (all four sites, filtered to 2000-2021) ────────────────────
cat("Processing CMIP6...\n")
nr1_cmip6 <- list(
  CESM2          = proc_cmip6(file.path(DATA_DIR, "cmip6", "CESM2_usnr1_monthly.csv"),         "CESM2"),
  `IPSL-CM6A-LR` = proc_cmip6(file.path(DATA_DIR, "cmip6", "IPSL-CM6A-LR_usnr1_monthly.csv"), "IPSL-CM6A-LR"),
  `UKESM1-0-LL`  = proc_cmip6(file.path(DATA_DIR, "cmip6", "UKESM1-0-LL_usnr1_monthly.csv"),  "UKESM1-0-LL")
)
mms_cmip6 <- list(
  CESM2          = proc_cmip6(file.path(DATA_DIR, "cmip6", "CESM2_usmms_monthly.csv"),         "CESM2"),
  `IPSL-CM6A-LR` = proc_cmip6(file.path(DATA_DIR, "cmip6", "IPSL-CM6A-LR_usmms_monthly.csv"), "IPSL-CM6A-LR"),
  `UKESM1-0-LL`  = proc_cmip6(file.path(DATA_DIR, "cmip6", "UKESM1-0-LL_usmms_monthly.csv"),  "UKESM1-0-LL")
)
detha_cmip6 <- list(
  CESM2          = proc_cmip6(file.path(DATA_DIR, "cmip6", "CESM2_detha_monthly.csv"),         "CESM2"),
  `IPSL-CM6A-LR` = proc_cmip6(file.path(DATA_DIR, "cmip6", "IPSL-CM6A-LR_detha_monthly.csv"), "IPSL-CM6A-LR"),
  `UKESM1-0-LL`  = proc_cmip6(file.path(DATA_DIR, "cmip6", "UKESM1-0-LL_detha_monthly.csv"),  "UKESM1-0-LL")
)
dksor_cmip6 <- list(
  CESM2          = proc_cmip6(file.path(DATA_DIR, "cmip6", "CESM2_dksor_monthly.csv"),         "CESM2"),
  `IPSL-CM6A-LR` = proc_cmip6(file.path(DATA_DIR, "cmip6", "IPSL-CM6A-LR_dksor_monthly.csv"), "IPSL-CM6A-LR"),
  `UKESM1-0-LL`  = proc_cmip6(file.path(DATA_DIR, "cmip6", "UKESM1-0-LL_dksor_monthly.csv"),  "UKESM1-0-LL")
)

# ── Assemble the data object passed to the dashboard ─────────────────────────
all_data <- list(
  `US-NR1` = list(
    meta    = list(
      label    = "US-NR1 -- Niwot Ridge, CO (ENF, subalpine)",
      site     = "US-NR1",
      nee_note = "NEE_CUT_REF (constant u* threshold; VUT not applied to this site)"
    ),
    ssem    = list(
      subdaily = nr1_subdaily,
      daily    = nr1_full$daily,
      monthly  = nr1_full$monthly,
      annual   = nr1_full$annual
    ),
    fluxnet    = nr1_fluxnet,
    fluxnet_sd = nr1_fluxnet_sd,
    fluxcom    = nr1_fluxcom,
    cmip6      = nr1_cmip6
  ),
  `US-MMS` = list(
    meta    = list(
      label    = "US-MMS -- Morgan Monroe State Forest, IN (DBF, temperate)",
      site     = "US-MMS",
      nee_note = "NEE_VUT_REF (variable u* threshold method)"
    ),
    ssem    = list(
      subdaily = mms_subdaily,
      daily    = mms_full$daily,
      monthly  = mms_full$monthly,
      annual   = mms_full$annual
    ),
    fluxnet    = mms_fluxnet,
    fluxnet_sd = mms_fluxnet_sd,
    fluxcom    = mms_fluxcom,
    cmip6      = mms_cmip6
  ),
  `DE-Tha` = list(
    meta    = list(
      label    = "DE-Tha -- Tharandt, Germany (ENF, European temperate coniferous)",
      site     = "DE-Tha",
      nee_note = "NEE_VUT_REF (variable u* threshold method)"
    ),
    ssem       = NULL,             # No SSEM run performed for this site
    fluxnet    = detha_fluxnet,
    fluxnet_sd = detha_fluxnet_sd,
    fluxcom    = detha_fluxcom,
    cmip6      = detha_cmip6
  ),
  `DK-Sor` = list(
    meta    = list(
      label    = "DK-Sor -- Sorø, Denmark (DBF, European temperate deciduous)",
      site     = "DK-Sor",
      nee_note = "NEE_VUT_REF (variable u* threshold method)"
    ),
    ssem       = NULL,             # No SSEM run performed for this site
    fluxnet    = dksor_fluxnet,
    fluxnet_sd = dksor_fluxnet_sd,
    fluxcom    = dksor_fluxcom,
    cmip6      = dksor_cmip6
  )
)

cat("\nSerializing to JSON...\n")
json_data <- toJSON(all_data, auto_unbox = TRUE, digits = 5, na = "null",
                    pretty = FALSE, force = TRUE)
cat(sprintf("  JSON size: %.1f MB\n", nchar(json_data, type="bytes") / 1e6))

# ─── Download / load Plotly.js ────────────────────────────────────────────────
cat("Loading Plotly.js...\n")
if (!file.exists(PLOTLY_CACHE) || file.size(PLOTLY_CACHE) < 1e6) {
  cat("  Downloading Plotly 2.26.2 from CDN...\n")
  tryCatch(
    download.file("https://cdn.plot.ly/plotly-2.26.2.min.js",
                  destfile = PLOTLY_CACHE, quiet = TRUE, mode = "wb"),
    error = function(e) stop("Failed to download Plotly.js: ", e$message,
                             "\n  Ensure internet access or pre-cache the file.")
  )
  cat(sprintf("  Cached at %s (%.1f MB)\n", PLOTLY_CACHE, file.size(PLOTLY_CACHE)/1e6))
} else {
  cat(sprintf("  Using cached %s (%.1f MB)\n", PLOTLY_CACHE, file.size(PLOTLY_CACHE)/1e6))
}
plotly_js <- paste(readLines(PLOTLY_CACHE, warn = FALSE), collapse = "\n")

# ─── HTML template ────────────────────────────────────────────────────────────
cat("Assembling HTML...\n")

css <- '
:root { --navy:#1a3a5c; --navy-lt:#2c5282; --cream:#f8f9fa; --border:#cdd5df; --txt:#1a202c; --muted:#718096; }
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:Georgia,serif;background:var(--cream);color:var(--txt);font-size:14px;line-height:1.4}
header{background:var(--navy);color:#fff;padding:14px 24px}
header h1{font-size:17px;font-weight:normal;letter-spacing:.02em}
.controls{background:#fff;border-bottom:1px solid var(--border);padding:10px 24px;display:flex;flex-wrap:wrap;gap:16px;align-items:flex-end}
.cg{display:flex;flex-direction:column;gap:4px}
.cl{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}
.br{display:flex;gap:3px}
.btn{border:1px solid var(--border);background:#fff;padding:4px 10px;cursor:pointer;font-size:12px;border-radius:3px;font-family:Georgia,serif}
.btn.on{background:var(--navy);color:#fff;border-color:var(--navy)}
.btn:hover:not(.on){background:#edf2f7}
select{border:1px solid var(--border);padding:5px 8px;font-size:13px;border-radius:3px;font-family:Georgia,serif}
.wrap{display:flex}
.sidebar{width:190px;min-width:190px;background:#fff;border-right:1px solid var(--border);padding:12px 14px;flex-shrink:0}
.sidebar h3{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em;margin-bottom:8px}
.cbl{display:flex;align-items:center;gap:6px;margin:5px 0;font-size:12px;cursor:pointer;user-select:none}
.cbl input{cursor:pointer}
.dot{width:11px;height:11px;border-radius:50%;flex-shrink:0}
#plotDiv{flex:1;min-height:450px}
.statsbar{background:#fff;border-top:1px solid var(--border);padding:10px 20px;display:flex;flex-wrap:wrap;gap:24px;align-items:center}
.stat .sl{font-size:10px;color:var(--muted);text-transform:uppercase}
.stat .sv{font-size:16px;font-weight:bold;color:var(--navy)}
.docs{margin:14px 20px 20px;background:#fff;border:1px solid var(--border);border-radius:4px}
.dh{padding:10px 16px;cursor:pointer;display:flex;justify-content:space-between;font-size:13px;font-weight:bold;color:var(--navy)}
.dh:hover{background:#edf2f7}
.db{padding:0 16px 16px;display:none;font-size:12px;line-height:1.6}
.db.open{display:block}
.db table{border-collapse:collapse;width:100%;margin:8px 0;font-size:11px}
.db td,.db th{border:1px solid var(--border);padding:5px 8px;vertical-align:top}
.db th{background:#edf2f7;font-weight:bold}
.cav{background:#fff8e1;border-left:3px solid #f6ad55;padding:6px 10px;margin:8px 0;border-radius:2px;font-size:11px}
footer{text-align:center;font-size:11px;color:var(--muted);padding:10px;border-top:1px solid var(--border)}
'

js_app <- '
const DATA = __JSON__;

/* ── Colour palette ─────────────────────────────────────────────────────── */
const C = {
  ssem:"#1a3a5c", fluxnet:"#c0392b", fluxcom:"#e67e22",
  cesm2:"#27ae60", ipsl:"#8e44ad", ukesm:"#2980b9",
  sw:"#e67e22", lw:"#a04000", le:"#2980b9", h_:"#c0392b"
};

/* ── Line width hierarchy ───────────────────────────────────────────────── */
/* FLUXNET observed: thick (3). SSEM median: medium (1.5).                  */
/* FLUXCOM: dashed medium (2). CMIP6 models: thin (1).                      */
const LW = { fluxnet: 3, ssem_med: 1.5, fluxcom: 2, cmip6: 1 };

/* ── Variable metadata ──────────────────────────────────────────────────── */
const VARS = {
  NEE:    {field:"nee",  ylab:"NEE (gC m-2 d-1)",  ylab_sd:"NEE (umol CO2 m-2 s-1)",  streams:["ssem","fluxnet","fluxcom","cmip6"]},
  GPP:    {field:"gpp",  ylab:"GPP (gC m-2 d-1)",  ylab_sd:"GPP (umol CO2 m-2 s-1)",  streams:["ssem","fluxnet","fluxcom","cmip6"]},
  Rh:     {field:"rh",   ylab:"Rh (gC m-2 d-1)",   ylab_sd:"Rh (umol CO2 m-2 s-1)",   streams:["ssem","cmip6"]},
  LAI:    {field:"lai",  ylab:"LAI (m2 m-2)",       ylab_sd:"LAI (m2 m-2)",             streams:["ssem","cmip6"]},
  ET:     {field:"et",   ylab:"ET (mm d-1)",         ylab_sd:null,                       streams:["fluxnet","fluxcom","cmip6"]},
  Energy: {field:null,   ylab:"Energy (W m-2)",      ylab_sd:null,                       streams:["fluxnet","cmip6"]}
};

let site="US-NR1", vari="NEE", ts="daily";

function setSite(s) {
  site = s;
  document.querySelectorAll("#siteBtns .btn").forEach(b =>
    b.classList.toggle("on", b.dataset.s === s));
  document.getElementById("siteLabel").textContent = DATA[s].meta.label;
  update();
}

function setVar(v) { vari = v; update(); }

function setTS(t) {
  ts = t;
  document.querySelectorAll("#tsBtns .btn").forEach(b =>
    b.classList.toggle("on", b.dataset.t === t));
  update();
}

function cb(id) { const el = document.getElementById(id); return el && el.checked; }

/* ── Trace builders ──────────────────────────────────────────────────────── */

/* Convert 6-digit hex colour to rgba() string with the given alpha (0–1).   */
/* Plotly requires rgba() or 6-digit hex; 8-digit hex (#RRGGBBAA) is not      */
/* reliably parsed by the tinycolor2 bundled in Plotly 2.26.2.                */
function hexToRgba(hex, alpha) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return "rgba(" + r + "," + g + "," + b + "," + alpha + ")";
}

/* Take every nth element from an array — used to downsample the CI ribbon    */
/* polygon so Plotly can fill it reliably on large multi-year records.         */
function downsample(arr, n) {
  const out = [];
  for (let i = 0; i < arr.length; i += n) out.push(arr[i]);
  return out;
}

/* Shaded ribbon for SSEM 95% CI — low opacity fill, no legend entry.         */
/* xRibbon: x coords for the fill polygon (may be coarser than xMed).         */
/* xMed:    x coords for the median line (full resolution).                   */
function ribbon(xRibbon, xMed, med, lo, hi, name, col) {
  return [
    {x: xRibbon.concat(xRibbon.slice().reverse()),
     y: hi.concat(lo.slice().reverse()),
     fill:"toself", fillcolor:hexToRgba(col, 0.16), line:{width:0},
     type:"scatter", mode:"lines", showlegend:false, hoverinfo:"skip", name:name+" CI"},
    {x: xMed, y:med, type:"scatter", mode:"lines",
     line:{color:col, width:LW.ssem_med}, name:name}
  ];
}

/* Solid line with explicit width and optional dash style */
function line_trace(x, y, col, name, dash, width) {
  return {x, y, type:"scatter", mode:"lines",
    line:{color:col, width:width||1.5, dash:dash||"solid"}, name};
}

/* Line + markers for data with discrete year points */
function lm_trace(x, y, col, name, dash, width) {
  return {x, y, type:"scatter", mode:"lines+markers",
    line:{color:col, width:width||LW.cmip6, dash:dash||"solid"}, marker:{size:4}, name};
}

/* ── Main trace builder ──────────────────────────────────────────────────── */
function getTraces() {
  const d  = DATA[site];
  const vc = VARS[vari];
  const f  = vc.field;
  const t  = [];

  /* ── Sub-daily (2008 representative year) ────────────────────────────── */
  if (ts === "subdaily") {
    /* SSEM median line (US-NR1 and US-MMS only; d.ssem is null for other sites) */
    const sd = d.ssem ? d.ssem.subdaily : null;
    if (sd && vc.streams.includes("ssem") && f && cb("cb_ssem_med") && sd[f])
      t.push(line_trace(sd.dates, sd[f], C.ssem, "SSEM 2008", "solid", LW.ssem_med));

    /* FLUXNET sub-daily 2008 — scatter, coloured by NEE QC flag (0-3) */
    if (cb("cb_fluxnet_sd") && d.fluxnet_sd) {
      const fsd = d.fluxnet_sd;
      /* QC colour key: 0=measured (black), 1=high-quality gap-fill (green),
         2=medium-quality (orange), 3=low-quality (red) */
      const QC_COL  = ["#000000", "#27ae60", "#e67e22", "#c0392b"];
      const QC_LABL = [
        "FLUXNET QC=0 (measured)",
        "FLUXNET QC=1 (gap-filled, high quality)",
        "FLUXNET QC=2 (gap-filled, medium quality)",
        "FLUXNET QC=3 (gap-filled, low quality)"
      ];
      if (vari === "NEE" && fsd.nee) {
        /* One trace per QC level so Plotly assigns a distinct legend entry */
        [0,1,2,3].forEach(q => {
          const idx = [];
          fsd.nee_qc.forEach((v,i) => { if (v === q) idx.push(i); });
          if (idx.length > 0)
            t.push({
              x: idx.map(i => fsd.dates[i]),
              y: idx.map(i => fsd.nee[i]),
              type:"scatter", mode:"markers",
              marker:{color:QC_COL[q], size:2, opacity:0.7},
              name:QC_LABL[q], showlegend:true
            });
        });
      }
      if (vari === "Energy") {
        /* Show SW, LE, H as lines; no QC colouring for energy */
        [["sw",C.sw,"SW_IN"],["le",C.le,"LE"],["h",C.h_,"H"]].forEach(([fld,col,nm]) => {
          if (fsd[fld]) t.push(line_trace(fsd.dates, fsd[fld], col, "FLUXNET "+nm, "solid", LW.fluxnet));
        });
      }
      if (vari === "ET" && fsd.et)
        t.push(line_trace(fsd.dates, fsd.et, C.fluxnet, "FLUXNET ET", "solid", LW.fluxnet));
    }
    return t;
  }

  /* ── Daily (full record) ─────────────────────────────────────────────── */
  if (ts === "daily") {
    /* d.ssem is null for sites without an SSEM run (DE-Tha, DK-Sor) */
    const dd = d.ssem ? d.ssem.daily : null;
    const fd = d.fluxnet.daily;

    /* SSEM ribbon / median line */
    if (dd && vc.streams.includes("ssem") && f && dd[f+"_med"]) {
      if (cb("cb_ssem_ci")) {
        /* Downsample CI ribbon to weekly (every 7th day) — reduces the closed */
        /* polygon from ~18,992 to ~2,714 points so Plotly fills it reliably.  */
        /* The median line stays at full daily resolution.                      */
        const step = 7;
        t.push(...ribbon(
          downsample(dd.dates, step), dd.dates, dd[f+"_med"],
          downsample(dd[f+"_lo"], step), downsample(dd[f+"_hi"], step),
          "SSEM", C.ssem));
      }
      else if (cb("cb_ssem_med"))
        t.push(line_trace(dd.dates, dd[f+"_med"], C.ssem, "SSEM", "solid", LW.ssem_med));
    }

    /* FLUXNET daily as thick line (lw=3), QC stored separately but not coloured */
    if (vc.streams.includes("fluxnet") && cb("cb_fluxnet")) {
      if (f && fd[f] && vari !== "Energy")
        t.push(line_trace(fd.dates, fd[f], C.fluxnet, "FLUXNET", "solid", LW.fluxnet));
      if (vari === "Energy") {
        [["sw",C.sw],["lw",C.lw],["le",C.le],["h",C.h_]].forEach(([fld,col]) => {
          if (fd[fld]) t.push(line_trace(fd.dates, fd[fld], col, fld.toUpperCase(), "solid", LW.fluxnet));
        });
      }
      if (vari === "ET" && fd.et)
        t.push(line_trace(fd.dates, fd.et, C.fluxnet, "FLUXNET ET", "solid", LW.fluxnet));
    }
    return t;
  }

  /* ── Monthly (full record) ───────────────────────────────────────────── */
  if (ts === "monthly") {
    /* d.ssem is null for sites without SSEM; guard before accessing .monthly */
    const sm  = d.ssem ? d.ssem.monthly : null;
    const fm  = d.fluxnet.monthly;
    const fc  = d.fluxcom.monthly;
    const cms = d.cmip6;

    if (sm && vc.streams.includes("ssem") && f && sm[f] && cb("cb_ssem_med"))
      t.push(line_trace(sm.dates, sm[f], C.ssem, "SSEM", "solid", LW.ssem_med));

    if (vc.streams.includes("fluxnet") && f && fm[f] && cb("cb_fluxnet") && vari!=="Energy")
      t.push(line_trace(fm.dates, fm[f], C.fluxnet, "FLUXNET", "solid", LW.fluxnet));

    if (vc.streams.includes("fluxcom") && f && fc[f] && cb("cb_fluxcom"))
      t.push(line_trace(fc.dates, fc[f], C.fluxcom, "FLUXCOM 2001-2021", "dash", LW.fluxcom));

    [["CESM2","cb_cesm2",C.cesm2],
     ["IPSL-CM6A-LR","cb_ipsl",C.ipsl],
     ["UKESM1-0-LL","cb_ukesm",C.ukesm]]
      .forEach(([m,cbid,col]) => {
        if (!cb(cbid) || !vc.streams.includes("cmip6")) return;
        const md = cms[m].monthly;
        const y  = vari==="Energy" ? md.le : (f ? md[f] : null);
        if (y) t.push(line_trace(md.dates, y, col, m, "dot", LW.cmip6));
        if (vari==="Energy" && md.h && cb(cbid))
          t.push(line_trace(md.dates, md.h, col+"99", m+" H", "dashdot", LW.cmip6));
      });

    return t;
  }

  /* ── Annual (full record) — lines throughout, no bar charts ─────────── */
  if (ts === "annual") {
    const fa  = d.fluxcom.annual;
    const cms = d.cmip6;

    /* SSEM annual: US-NR1 and US-MMS only; d.ssem.annual absent for other sites */
    if (d.ssem && d.ssem.annual && vc.streams.includes("ssem") && f && cb("cb_ssem_med")) {
      const ann = d.ssem.annual;
      const yv  = f==="lai" ? ann.lai_avg : (f ? ann[f] : null);
      if (yv) t.push(lm_trace(ann.year.map(String), yv, C.ssem, "SSEM", "solid", LW.ssem_med));
    }

    /* FLUXNET annual: thick line+markers */
    if (vc.streams.includes("fluxnet") && cb("cb_fluxnet") && f) {
      const ann_fn = d.fluxnet.annual;
      const yv = ann_fn[f];
      if (yv) t.push(lm_trace(ann_fn.year.map(String), yv, C.fluxnet, "FLUXNET", "solid", LW.fluxnet));
    }

    /* FLUXCOM annual: dashed medium line */
    if (vc.streams.includes("fluxcom") && f && fa.year && cb("cb_fluxcom")) {
      const yv = f==="lai" ? null : fa[f];
      if (yv) t.push(line_trace(fa.year.map(String), yv, C.fluxcom, "FLUXCOM", "dash", LW.fluxcom));
    }

    /* CMIP6 annual: thin lines per model */
    [["CESM2","cb_cesm2",C.cesm2],
     ["IPSL-CM6A-LR","cb_ipsl",C.ipsl],
     ["UKESM1-0-LL","cb_ukesm",C.ukesm]]
      .forEach(([m,cbid,col]) => {
        if (!cb(cbid) || !vc.streams.includes("cmip6")) return;
        const ann = cms[m].annual;
        const yv  = f==="lai" ? ann.lai_avg : (f ? ann[f] : null);
        if (yv) t.push(line_trace(ann.year.map(String), yv, col, m, "dot", LW.cmip6));
      });
  }

  return t;
}

/* ── Layout ──────────────────────────────────────────────────────────────── */
function getLayout() {
  const vc   = VARS[vari];
  const isSd = ts === "subdaily";
  const isAnn= ts === "annual";
  const ylab = isSd ? (vc.ylab_sd || vc.ylab)
                    : isAnn && vari!=="LAI" && vari!=="Energy"
                      ? vc.ylab.replace("d-1","yr-1")
                      : vc.ylab;
  const tsLabel = ts === "subdaily"
    ? "Sub-daily (2008 representative year, SSEM only)"
    : ts.charAt(0).toUpperCase() + ts.slice(1) + " (full record)";
  const optEl  = document.getElementById("varSel");
  const varTxt = optEl ? optEl.options[optEl.selectedIndex].text : vari;
  return {
    margin:{l:65,r:20,t:40,b:60},
    title:{text:site+" -- "+varTxt+" ("+tsLabel+")",
           font:{size:14,color:"#1a3a5c"}},
    xaxis:{title:isAnn?"Year":"Date",showgrid:true,gridcolor:"#e2e8f0",zeroline:false},
    yaxis:{title:ylab,showgrid:true,gridcolor:"#e2e8f0",zeroline:true,zerolinecolor:"#cbd5e0"},
    legend:{orientation:"h",x:0,y:-0.18,font:{size:11}},
    plot_bgcolor:"#ffffff", paper_bgcolor:"#ffffff",
    font:{family:"Georgia, serif",size:12},
    hovermode:"x unified"
  };
}

/* ── Cost functions (SSEM vs FLUXNET, daily, NEE and GPP only) ───────────── */
function updateStats() {
  const f = VARS[vari].field;
  const na = v => { document.getElementById("val_"+v).textContent="--"; };
  const set = (v,x) => { document.getElementById("val_"+v).textContent=x; };

  /* Stats require SSEM daily data — guard for sites without SSEM (DE-Tha, DK-Sor) */
  const dd = DATA[site].ssem ? DATA[site].ssem.daily : null;
  if (!dd || !f || !["NEE","GPP"].includes(vari) || ts!=="daily") {
    ["rmse","bias","r"].forEach(na);
    set("n_pts","--");
    return;
  }
  const fd = DATA[site].fluxnet.daily;
  const s  = dd[f+"_med"], o = fd[f];
  if (!s || !o) { ["rmse","bias","r"].forEach(na); return; }

  /* Match by date string to handle any gaps in either series */
  const dmap = {};
  for (let i=0; i<fd.dates.length; i++) if (o[i]!=null && !isNaN(o[i])) dmap[fd.dates[i]] = o[i];
  const pairs = [];
  for (let i=0; i<dd.dates.length; i++) {
    const ov = dmap[dd.dates[i]];
    if (s[i]!=null && !isNaN(s[i]) && ov!=null) pairs.push([s[i], ov]);
  }

  if (!pairs.length) { ["rmse","bias","r"].forEach(na); return; }
  const n  = pairs.length;
  const ms = pairs.reduce((a,p)=>a+p[0],0)/n;
  const mo = pairs.reduce((a,p)=>a+p[1],0)/n;
  const rmse = Math.sqrt(pairs.reduce((a,p)=>a+Math.pow(p[0]-p[1],2),0)/n);
  const bias = ms-mo;
  const ss = pairs.reduce((a,p)=>a+(p[0]-ms)*(p[1]-mo),0);
  const vs = Math.sqrt(pairs.reduce((a,p)=>a+Math.pow(p[0]-ms,2),0));
  const vo = Math.sqrt(pairs.reduce((a,p)=>a+Math.pow(p[1]-mo,2),0));
  const r  = vs>0&&vo>0 ? ss/(vs*vo) : NaN;

  set("n_pts", n);
  set("rmse", rmse.toFixed(3)+" gC m-2 d-1");
  set("bias", (bias>=0?"+":"")+bias.toFixed(3)+" gC m-2 d-1");
  set("r",    isNaN(r)?"--":r.toFixed(3));
}

/* ── Update ──────────────────────────────────────────────────────────────── */
function update() {
  Plotly.react("plotDiv", getTraces(), getLayout(), {responsive:true, displaylogo:false});
  updateStats();
}

function toggleDocs() {
  const b = document.getElementById("docsBody");
  const a = document.getElementById("darrow");
  const o = b.classList.toggle("open");
  a.textContent = o ? "\\u25BC" : "\\u25BA";
}

// ── Init ──────────────────────────────────────────────────────────────────────
document.getElementById("siteLabel").textContent = DATA["US-NR1"].meta.label;
update();
'

build_date   <- format(Sys.time(), "%Y-%m-%d %H:%M")
js_with_data <- gsub("__JSON__", json_data, js_app, fixed = TRUE)

html_head <- paste0(
'<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>FluxCourseForecast 2026 -- Model-Data Comparison Dashboard</title>
<style>',
css,
'</style>
</head>
<body>
<header>
  <h1>FluxCourseForecast 2026 -- Model-Data Comparison Dashboard</h1>
</header>'
)

html_controls <- '
<div class="controls">
  <div class="cg">
    <span class="cl">Site</span>
    <div class="br" id="siteBtns">
      <button class="btn on" data-s="US-NR1" onclick="setSite(\'US-NR1\')">US-NR1</button>
      <button class="btn"    data-s="US-MMS" onclick="setSite(\'US-MMS\')">US-MMS</button>
      <button class="btn"    data-s="DE-Tha" onclick="setSite(\'DE-Tha\')">DE-Tha</button>
      <button class="btn"    data-s="DK-Sor" onclick="setSite(\'DK-Sor\')">DK-Sor</button>
    </div>
  </div>
  <div class="cg">
    <span class="cl">Variable</span>
    <select id="varSel" onchange="setVar(this.value)">
      <option value="NEE">NEE (net ecosystem exchange)</option>
      <option value="GPP">GPP (gross primary production)</option>
      <option value="Rh">Rh (heterotrophic respiration)</option>
      <option value="LAI">LAI (leaf area index)</option>
      <option value="ET">ET (evapotranspiration)</option>
      <option value="Energy">Energy balance (SW, LW, LE, H)</option>
    </select>
  </div>
  <div class="cg">
    <span class="cl">Timescale</span>
    <div class="br" id="tsBtns">
      <button class="btn"    data-t="subdaily" onclick="setTS(\'subdaily\')">Sub-daily</button>
      <button class="btn on" data-t="daily"    onclick="setTS(\'daily\')">Daily</button>
      <button class="btn"    data-t="monthly"  onclick="setTS(\'monthly\')">Monthly</button>
      <button class="btn"    data-t="annual"   onclick="setTS(\'annual\')">Annual</button>
    </div>
  </div>
  <div class="cg" style="margin-left:auto">
    <span class="cl">Selected site</span>
    <span id="siteLabel" style="font-size:12px;font-weight:bold;color:#1a3a5c;max-width:320px"></span>
  </div>
</div>

<div class="wrap">
  <div class="sidebar">
    <h3>Data Streams</h3>
    <label class="cbl">
      <input type="checkbox" id="cb_ssem_med" checked onchange="update()">
      <span class="dot" style="background:#1a3a5c"></span>SSEM median
    </label>
    <label class="cbl">
      <input type="checkbox" id="cb_ssem_ci" checked onchange="update()">
      <span class="dot" style="background:#1a3a5c;opacity:.25"></span>SSEM 95% CI
    </label>
    <label class="cbl">
      <input type="checkbox" id="cb_fluxnet" checked onchange="update()">
      <span class="dot" style="background:#c0392b"></span>FLUXNET daily obs
    </label>
    <label class="cbl">
      <input type="checkbox" id="cb_fluxnet_sd" checked onchange="update()">
      <span class="dot" style="background:#c0392b;opacity:.6"></span>FLUXNET sub-daily (2008)
    </label>
    <label class="cbl">
      <input type="checkbox" id="cb_fluxcom" checked onchange="update()">
      <span class="dot" style="background:#e67e22"></span>FLUXCOM (0.5&deg;)
    </label>
    <label class="cbl">
      <input type="checkbox" id="cb_cesm2" checked onchange="update()">
      <span class="dot" style="background:#27ae60"></span>CMIP6 CESM2
    </label>
    <label class="cbl">
      <input type="checkbox" id="cb_ipsl" checked onchange="update()">
      <span class="dot" style="background:#8e44ad"></span>CMIP6 IPSL
    </label>
    <label class="cbl">
      <input type="checkbox" id="cb_ukesm" checked onchange="update()">
      <span class="dot" style="background:#2980b9"></span>CMIP6 UKESM
    </label>
  </div>
  <div id="plotDiv"></div>
</div>

<div class="statsbar">
  <span style="font-size:11px;color:#718096">SSEM vs FLUXNET full-record daily (n=<span id="n_pts">--</span>; NEE and GPP only)</span>
  <div class="stat"><div class="sl">RMSE</div><div class="sv" id="val_rmse">--</div></div>
  <div class="stat"><div class="sl">Bias (SSEM minus obs)</div><div class="sv" id="val_bias">--</div></div>
  <div class="stat"><div class="sl">Pearson r</div><div class="sv" id="val_r">--</div></div>
</div>'

html_docs <- '
<div class="docs">
  <div class="dh" onclick="toggleDocs()">
    Data Stream Reference and Caveats
    <span id="darrow">&#9658;</span>
  </div>
  <div class="db" id="docsBody">
    <table>
      <tr><th>Stream</th><th>Source</th><th>Temporal res.</th><th>Spatial scale</th><th>Units (dashboard)</th><th>Available variables</th></tr>
      <tr><td>SSEM median / CI</td><td>Super Simple Ecosystem Model (Dietze lab)</td><td>Sub-daily (2008 representative year); daily / monthly / annual (full record 2000–2023)</td><td>Point (forest stand, ~1 ha)</td><td>gC m-2 d-1 (daily+); umol m-2 s-1 (sub-daily)</td><td>GPP, NEE, Rh, LAI — US-NR1 and US-MMS only</td></tr>
      <tr><td>FLUXNET daily obs</td><td>AmeriFlux / ICOS FLUXNET product: all four sites</td><td>Daily (DD product, 2000-2025)</td><td>Tower footprint (~0.5-2 km2)</td><td>gC m-2 d-1 (C fluxes); W m-2 (energy); mm d-1 (ET)</td><td>NEE, GPP, RECO, LE, H, SW_IN, LW_IN, ET</td></tr>
      <tr><td>FLUXNET sub-daily (2008)</td><td>AmeriFlux / ICOS FLUXNET product: all four sites</td><td>Sub-daily (2008 only; thinned to every 4th step)</td><td>Tower footprint</td><td>umol m-2 s-1 (NEE); W m-2 (LE, H, SW)</td><td>NEE (QC-coloured), LE, H, SW_IN, ET</td></tr>
      <tr><td>FLUXCOM</td><td>FLUXCOM-X-BASE (Nelson et al. 2024, Biogeosciences)</td><td>Monthly (2001-2021)</td><td>0.5 deg grid cell (~50 km)</td><td>gC m-2 d-1 (mean daily rate for month)</td><td>GPP, NEE, TER, ET</td></tr>
      <tr><td>CMIP6 CESM2</td><td>CESM2 (NCAR), Pangeo CMIP6 cloud archive</td><td>Monthly (2000-2021)</td><td>~1 deg grid cell (~100 km)</td><td>gC m-2 d-1 (mean daily rate); W m-2 (energy)</td><td>GPP, Rh, NEE, LAI, LE, H, ET</td></tr>
      <tr><td>CMIP6 IPSL-CM6A-LR</td><td>IPSL-CM6A-LR (IPSL), Pangeo CMIP6 cloud archive</td><td>Monthly</td><td>~1 deg grid cell</td><td>same as CESM2</td><td>same as CESM2</td></tr>
      <tr><td>UKESM1-0-LL</td><td>UKESM1-0-LL (MOHC), Pangeo CMIP6 cloud archive</td><td>Monthly (historical ends ~2014)</td><td>~1 deg grid cell</td><td>same as CESM2</td><td>same as CESM2</td></tr>
    </table>
    <div class="cav"><strong>Sub-daily timescale:</strong> 2008 only. SSEM output is available for US-NR1 and US-MMS. FLUXNET sub-daily observations (thinned to every 4th timestep) are available for all four sites. NEE points are colour-coded by QC flag: black=measured (QC=0), green=high-quality gap-fill (QC=1), orange=medium-quality (QC=2), red=low-quality (QC=3).</div>
    <div class="cav"><strong>CESM2 scenario:</strong> SSP3-7.0 (ssp370) was used for CESM2 instead of SSP2-4.5 because the SSP2-4.5 run for the US-MMS grid cell was unavailable at time of extraction. Future-period CESM2 projections use a higher-emissions pathway than the other models.</div>
    <div class="cav"><strong>UKESM1-0-LL:</strong> Only historical output (ending approximately 2014) is present in the pre-extracted CSVs. Future-period months are absent. This is a data-availability limitation, not a model property.</div>
    <div class="cav"><strong>US-NR1 NEE:</strong> NEE_CUT_REF (constant u* threshold method) is used instead of NEE_VUT_REF because the variable u* method was not applied to this site in the provided data product. GPP and RECO use the corresponding CUT nighttime-partitioning method.</div>
    <div class="cav"><strong>Spatial scale hierarchy:</strong> SSEM simulates one forest stand (tower footprint, sub-km). FLUXCOM integrates machine-learning estimates across a 0.5 deg cell (~50 km). CMIP6 models integrate across ~1 deg (~100 km). Absolute magnitude differences between streams partly reflect this spatial aggregation, not only model error.</div>
    <div class="cav"><strong>CMIP6 NEE derivation:</strong> NEE shown here is computed as Ra + Rh - GPP from model output, which equals -NEP. This approximation neglects land-use change fluxes and lateral carbon transport included in the model\'s NBP variable.</div>
    <p style="margin-top:10px;font-size:11px;color:#718096">
      SSEM code: Dietze lab, BU (mdietze/FluxCourseForecast). FLUXNET data: CC-BY-4.0, AmeriFlux network and ICOS.
      FLUXCOM data: Nelson et al. (2024), doi:10.18160/5NZG-JMJE, CCBY4.
      CMIP6 data: respective modelling groups, PCMDI/CMIP6 terms of use.
      Sites: US-NR1 (Niwot Ridge), US-MMS (Morgan Monroe), DE-Tha (Tharandt), DK-Sor (Sor&oslash;). Data 2000&ndash;2025.
    </p>
  </div>
</div>'

html_body <- paste0(
  html_head,
  html_controls,
  html_docs,
  "\n<footer>FluxCourseForecast 2026 &mdash; Bloomington, Indiana &mdash; built ", build_date, "</footer>\n\n",
  "<script>\n", plotly_js, "\n</script>\n",
  "<script>\n", js_with_data, "\n</script>\n",
  "</body>\n</html>\n"
)

# ─── Write output ─────────────────────────────────────────────────────────────
writeLines(html_body, OUT_HTML)
sz_mb <- file.size(OUT_HTML) / 1e6
cat(sprintf("\nOutput: %s (%.1f MB)\n", OUT_HTML, sz_mb))
if (sz_mb > 20) {
  cat("WARNING: file exceeds 20 MB — may be large for distribution.\n")
} else {
  cat("File size is within the 20 MB distribution limit.\n")
}
cat("Done.\n")
